// Generated by CoffeeScript 1.7.1
define(['jquery'], function($) {
  var ScreenController;
  return ScreenController = (function() {
    function ScreenController() {}

    ScreenController.prototype.show = function() {
      return console.log("Show");
    };

    ScreenController.prototype.hide = function() {
      return console.log("Hide");
    };

    return ScreenController;

  })();
});
