// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'app/controller/screen'], function($, ScreenController) {
  var Screen2Controller;
  return Screen2Controller = (function(_super) {
    __extends(Screen2Controller, _super);

    function Screen2Controller() {
      return Screen2Controller.__super__.constructor.apply(this, arguments);
    }

    return Screen2Controller;

  })(ScreenController);
});
