// Generated by CoffeeScript 1.7.1
define(['jquery'], function($) {
  var ScreenController;
  return ScreenController = (function() {
    function ScreenController() {}

    ScreenController.prototype.show = function() {
      console.log("Show");
      return this.view.show();
    };

    ScreenController.prototype.hide = function() {
      console.log("Hide");
      return this.view.hide();
    };

    ScreenController.prototype.setView = function(view) {
      this.view = view;
    };

    return ScreenController;

  })();
});
