// Generated by CoffeeScript 1.7.1
require.config({
  paths: {
    jquery: 'vendor/jquery-2.1.0'
  }
});

require(['jquery', 'app/controller/main'], function($, Application) {
  return $(document).ready(function() {
    var app;
    app = new Application();
    return app.launch();
  });
});
