// Generated by CoffeeScript 1.7.1
var __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

define(['jquery', 'app/view/screen'], function($, Screen) {
  var Screen1View;
  return Screen1View = (function(_super) {
    __extends(Screen1View, _super);

    function Screen1View() {
      return Screen1View.__super__.constructor.apply(this, arguments);
    }

    return Screen1View;

  })(Screen);
});
