// Generated by CoffeeScript 1.7.1
define(['jquery'], function($) {
  var View;
  return View = (function() {
    function View(selector) {
      this.selector = selector;
    }

    View.prototype.show = function() {
      return $(this.selector).show();
    };

    View.prototype.hide = function() {
      return $(this.selector).hide();
    };

    return View;

  })();
});
